INSERT INTO produtos (nome, representante, categoria, dimensao, valor, status, estoque, unidade_medida, multiplos_venda) VALUES
('ALGUIDAR 1', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 5cm, D.S: 18cm, D.I: 9cm', 8.4, 'Ativo', 0, 'Un', 1),
('ALGUIDAR 2', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 6cm, D.S: 22cm, D.I: 10,5cm', 9.1, 'Ativo', 0, 'Un', 1),
('ALGUIDAR 3', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 6cm, D.S: 26cm, D.I: 15cm', 10.9, 'Ativo', 0, 'Un', 1),
('ALGUIDAR 4', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7cm, D.S: 31cm, D.I: 17cm', 14.1, 'Ativo', 0, 'Un', 1),
('ALGUIDAR 5', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 35cm, D.I: 18cm', 16.2, 'Ativo', 0, 'Un', 1),
('ALGUIDAR 6', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 40cm, D.I: 21,5cm', 23.5, 'Ativo', 0, 'Un', 1),
('AMERICANO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 9cm', 5.7, 'Ativo', 0, 'Un', 1),
('AMERICANO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 9cm', 7.6, 'Ativo', 0, 'Un', 1),
('AMERICANO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 9cm', 9.3, 'Ativo', 0, 'Un', 1),
('AMERICANO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 16cm, D.S: 21cm, D.I: 12,5cm', 9.1, 'Ativo', 0, 'Un', 1),
('AMERICANO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 16cm, D.S: 21cm, D.I: 12,5cm', 12, 'Ativo', 0, 'Un', 1),
('AMERICANO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 16cm, D.S: 21cm, D.I: 12,5cm', 14.6, 'Ativo', 0, 'Un', 1),
('AMERICANO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20,5cm, D.S: 25cm, D.I: 14,5cm', 16.2, 'Ativo', 0, 'Un', 1),
('AMERICANO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20,5cm, D.S: 25cm, D.I: 14,5cm', 21.4, 'Ativo', 0, 'Un', 1),
('AMERICANO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20,5cm, D.S: 25cm, D.I: 14,5cm', 26.2, 'Ativo', 0, 'Un', 1),
('AMERICANO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 29cm, D.I: 17cm', 24, 'Ativo', 0, 'Un', 1),
('AMERICANO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 29cm, D.I: 17cm', 31.6, 'Ativo', 0, 'Un', 1),
('AMERICANO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 29cm, D.I: 17cm', 38.7, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7cm, D.S: 11cm, D.I: 5cm', 4.7, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7cm, D.S: 11cm, D.I: 5cm', 6.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7cm, D.S: 11cm, D.I: 5cm', 7.7, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 6,5cm', 5.7, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 6,5cm', 7.6, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 15cm, D.I: 6,5cm', 9.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 20cm, D.I: 9cm', 6.8, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 20cm, D.I: 9cm', 9.1, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 20cm, D.I: 9cm', 11.1, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 22cm, D.I: 12cm', 13.2, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 22cm, D.I: 12cm', 17.4, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 22cm, D.I: 12cm', 21.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 5 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 28cm, D.I: 16cm', 20, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 5 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 28cm, D.I: 16cm', 26.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 5 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 28cm, D.I: 16cm', 32.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 6 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 18cm', 30.3, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 6 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 18cm', 39.9, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 6 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 18cm', 48.9, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 7 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 36cm, D.I: 25cm', 51.4, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 7 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 36cm, D.I: 25cm', 67.7, 'Ativo', 0, 'Un', 1),
('AQUÁRIO 7 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 36cm, D.I: 25cm', 82.9, 'Ativo', 0, 'Un', 1),
('AREKA 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 41cm, D.I: 24,5cm', 37.5, 'Ativo', 0, 'Un', 1),
('AREKA 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 41cm, D.I: 24,5cm', 49.4, 'Ativo', 0, 'Un', 1),
('AREKA 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 41cm, D.I: 24,5cm', 60.5, 'Ativo', 0, 'Un', 1),
('AREKA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 49cm, D.I: 28,5cm', 75.5, 'Ativo', 0, 'Un', 1),
('AREKA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 49cm, D.I: 28,5cm', 99.4, 'Ativo', 0, 'Un', 1),
('AREKA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 49cm, D.I: 28,5cm', 121.8, 'Ativo', 0, 'Un', 1),
('BACIA AÉREA - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 20.8, 'Ativo', 0, 'Un', 1),
('BACIA AÉREA - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 27.5, 'Ativo', 0, 'Un', 1),
('BACIA AÉREA - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 33.7, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 22.5, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 29.7, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17,5cm, D.S: 28cm, D.I: 15cm', 36.4, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 36cm, D.I: 22,5cm', 29.8, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 36cm, D.I: 22,5cm', 39.3, 'Ativo', 0, 'Un', 1),
('BACIA RENDA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 36cm, D.I: 22,5cm', 48.1, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7,5cm, D.S: 27cm, D.I: 15,5cm', 18.2, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7,5cm, D.S: 27cm, D.I: 15,5cm', 24, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 7,5cm, D.S: 27cm, D.I: 15,5cm', 29.5, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 36cm, D.I: 21,5cm', 25.8, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 36cm, D.I: 21,5cm', 34, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 36cm, D.I: 21,5cm', 41.7, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 42cm, D.I: 26cm', 35.7, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 42cm, D.I: 26cm', 47.1, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 42cm, D.I: 26cm', 57.6, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 47cm, D.I: 30,5cm', 46.3, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 47cm, D.I: 30,5cm', 60.9, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 47cm, D.I: 30,5cm', 74.7, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 60cm, D.I: 40cm', 76.1, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 60cm, D.I: 40cm', 100.2, 'Ativo', 0, 'Un', 1),
('BACIA JAPONESA 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 60cm, D.I: 40cm', 122.8, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 22cm, D.I: 18cm', 18.2, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 22cm, D.I: 18cm', 24, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 22cm, D.I: 18cm', 29.5, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 29,5cm, D.I: 23cm', 25.8, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 29,5cm, D.I: 23cm', 34, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 29,5cm, D.I: 23cm', 41.7, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 38cm, D.I: 31cm', 35.7, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 38cm, D.I: 31cm', 47.1, 'Ativo', 0, 'Un', 1),
('BACIA ADENIUM 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 38cm, D.I: 31cm', 57.6, 'Ativo', 0, 'Un', 1),
('BALLY 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 52cm, D.S: 34cm, D.I: 30cm', 59.3, 'Ativo', 0, 'Un', 1),
('BALLY 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 52cm, D.S: 34cm, D.I: 30cm', 78, 'Ativo', 0, 'Un', 1),
('BALLY 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 52cm, D.S: 34cm, D.I: 30cm', 95.7, 'Ativo', 0, 'Un', 1),
('BALLY 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 36cm, D.I: 30cm', 82.9, 'Ativo', 0, 'Un', 1),
('BALLY 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 36cm, D.I: 30cm', 109.2, 'Ativo', 0, 'Un', 1),
('BALLY 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 36cm, D.I: 30cm', 133.8, 'Ativo', 0, 'Un', 1),
('BALLY 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 69cm, D.S: 40cm, D.I: 33cm', 104.6, 'Ativo', 0, 'Un', 1),
('BALLY 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 69cm, D.S: 40cm, D.I: 33cm', 137.7, 'Ativo', 0, 'Un', 1),
('BALLY 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 69cm, D.S: 40cm, D.I: 33cm', 166.8, 'Ativo', 0, 'Un', 1),
('BALLY 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 84cm, D.S: 38cm, D.I: 35cm', 156, 'Ativo', 0, 'Un', 1),
('BALLY 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 84cm, D.S: 38cm, D.I: 35cm', 205.3, 'Ativo', 0, 'Un', 1),
('BALLY 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 84cm, D.S: 38cm, D.I: 35cm', 251.7, 'Ativo', 0, 'Un', 1),
('BALLY 5 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 94cm, D.S: 43cm, D.I: 35cm', 221.1, 'Ativo', 0, 'Un', 1),
('BALLY 5 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 94cm, D.S: 43cm, D.I: 35cm', 290.9, 'Ativo', 0, 'Un', 1),
('BALLY 5 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 94cm, D.S: 43cm, D.I: 35cm', 356.6, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 26cm, D.I: 17,5cm', 33.1, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 26cm, D.I: 17,5cm', 43.6, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 26cm, D.I: 17,5cm', 53.4, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 32cm, D.I: 24,5cm', 55.7, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 32cm, D.I: 24,5cm', 73.4, 'Ativo', 0, 'Un', 1),
('BAÚ LISO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 32cm, D.S: 32cm, D.I: 24,5cm', 89.4, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 18cm, D.I: 16cm', 11.8, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 18cm, D.I: 16cm', 15.6, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 12cm, D.S: 18cm, D.I: 16cm', 19.1, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 25cm, D.I: 20,5cm', 18.1, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 25cm, D.I: 20,5cm', 23.9, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 25cm, D.I: 20,5cm', 29.3, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 29cm, D.I: 23,5cm', 25.7, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 29cm, D.I: 23,5cm', 33.9, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 29cm, D.I: 23,5cm', 41.5, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 36cm, D.I: 30cm', 31.2, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 36cm, D.I: 30cm', 41.1, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 36cm, D.I: 30cm', 50.3, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 44cm, D.I: 35,5cm', 55.5, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 44cm, D.I: 35,5cm', 73.1, 'Ativo', 0, 'Un', 1),
('BEGÔNIA 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 44cm, D.I: 35,5cm', 89.5, 'Ativo', 0, 'Un', 1),
('BELGA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 39cm, D.I: 25cm', 76.1, 'Ativo', 0, 'Un', 1),
('BELGA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 39cm, D.I: 25cm', 100.2, 'Ativo', 0, 'Un', 1),
('BELGA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 35cm, D.S: 39cm, D.I: 25cm', 122.8, 'Ativo', 0, 'Un', 1),
('BELGA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 49cm, D.I: 32,5cm', 117.1, 'Ativo', 0, 'Un', 1),
('BELGA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 49cm, D.I: 32,5cm', 154.1, 'Ativo', 0, 'Un', 1),
('BELGA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 49cm, D.I: 32,5cm', 188.8, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 18cm, D.I: 71cm', 40.9, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 18cm, D.I: 71cm', 53.9, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 23cm, D.I: 84cm', 53.9, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 23cm, D.I: 84cm', 70.9, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 3cm, D.S: 30cm, D.I: 96cm', 78.4, 'Ativo', 0, 'Un', 1),
('BOLA ESTRELA - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 3cm, D.S: 30cm, D.I: 96cm', 103.3, 'Ativo', 0, 'Un', 1),
('CACHEPOT BALLY - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15,5cm, D.S: 18cm, D.I: 16cm', 11.8, 'Ativo', 0, 'Un', 1),
('CACHEPOT BALLY - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15,5cm, D.S: 18cm, D.I: 16cm', 15.6, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 12,5cm, D.I: 9cm', 7.2, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 12,5cm, D.I: 9cm', 9.5, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15cm, D.S: 17cm, D.I: 13,5cm', 11.9, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15cm, D.S: 17cm, D.I: 13,5cm', 15.7, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 24cm, D.I: 17cm', 20, 'Ativo', 0, 'Un', 1),
('CACHEPOT ESFERA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 24cm, D.I: 17cm', 26.3, 'Ativo', 0, 'Un', 1),
('CALDEIRÃO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 28cm, D.I: 30cm', 33.4, 'Ativo', 0, 'Un', 1),
('CALDEIRÃO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 28cm, D.I: 30cm', 44, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 14cm, D.I: 14cm', 11.3, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 14cm, D.I: 14cm', 14.3, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 14cm, D.I: 14cm', 18.2, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 18cm, D.I: 17cm', 16, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 18cm, D.I: 17cm', 21.1, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 18cm, D.I: 17cm', 25.9, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 24cm, D.I: 22cm', 23.9, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 24cm, D.I: 22cm', 31.5, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 29cm, D.S: 24cm, D.I: 22cm', 38.6, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 33cm, D.I: 27cm', 35.2, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 33cm, D.I: 27cm', 46.3, 'Ativo', 0, 'Un', 1),
('CILINDRO ALTO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 33cm, D.I: 27cm', 56.7, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 27cm, D.I: 24,5cm', 16.7, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 27cm, D.I: 24,5cm', 22.1, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 27cm, D.I: 24,5cm', 27.1, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 30cm, D.I: 30cm', 22.1, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 30cm, D.I: 30cm', 29.2, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 30cm, D.I: 30cm', 35.7, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 27cm, D.S: 38cm, D.I: 37cm', 34, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 27cm, D.S: 38cm, D.I: 37cm', 44.7, 'Ativo', 0, 'Un', 1),
('CILINDRO BAIXO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 27cm, D.S: 38cm, D.I: 37cm', 54.8, 'Ativo', 0, 'Un', 1),
('COMUM 01 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 11cm, D.I: 6cm', 3.9, 'Ativo', 0, 'Un', 1),
('COMUM 01 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 11cm, D.I: 6cm', 5.2, 'Ativo', 0, 'Un', 1),
('COMUM 01 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 11cm, D.I: 6cm', 6.3, 'Ativo', 0, 'Un', 1),
('COMUM 02 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 13cm, D.I: 7,5cm', 5.1, 'Ativo', 0, 'Un', 1),
('COMUM 02 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 13cm, D.I: 7,5cm', 6.7, 'Ativo', 0, 'Un', 1),
('COMUM 02 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 13cm, D.I: 7,5cm', 8.2, 'Ativo', 0, 'Un', 1),
('COMUM 03 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 5.3, 'Ativo', 0, 'Un', 1),
('COMUM 03 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 6.9, 'Ativo', 0, 'Un', 1),
('COMUM 03 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 8.5, 'Ativo', 0, 'Un', 1),
('COMUM 05 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 7.1, 'Ativo', 0, 'Un', 1),
('COMUM 05 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 9.4, 'Ativo', 0, 'Un', 1),
('COMUM 05 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 11.5, 'Ativo', 0, 'Un', 1),
('COMUM 06 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 9.2, 'Ativo', 0, 'Un', 1),
('COMUM 06 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 12.1, 'Ativo', 0, 'Un', 1),
('COMUM 06 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 14.8, 'Ativo', 0, 'Un', 1),
('COMUM 07 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 26cm, D.I: 13,5cm', 13.6, 'Ativo', 0, 'Un', 1),
('COMUM 07 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 26cm, D.I: 13,5cm', 17.9, 'Ativo', 0, 'Un', 1),
('COMUM 07 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 23cm, D.S: 26cm, D.I: 13,5cm', 22, 'Ativo', 0, 'Un', 1),
('COMUM 08 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 28cm, D.I: 15,5cm', 16.1, 'Ativo', 0, 'Un', 1),
('COMUM 08 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 28cm, D.I: 15,5cm', 21.3, 'Ativo', 0, 'Un', 1),
('COMUM 08 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 28cm, D.I: 15,5cm', 26, 'Ativo', 0, 'Un', 1),
('COMUM 10 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 32cm, D.I: 19cm', 21.6, 'Ativo', 0, 'Un', 1),
('COMUM 10 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 32cm, D.I: 19cm', 28.4, 'Ativo', 0, 'Un', 1),
('COMUM 10 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 32cm, D.I: 19cm', 34.8, 'Ativo', 0, 'Un', 1),
('COMUM 12 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 23,5cm', 34.7, 'Ativo', 0, 'Un', 1),
('COMUM 12 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 23,5cm', 45.8, 'Ativo', 0, 'Un', 1),
('COMUM 12 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 23,5cm', 56.1, 'Ativo', 0, 'Un', 1),
('COMUM 14 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 41cm, D.I: 26,5cm', 63.1, 'Ativo', 0, 'Un', 1),
('COMUM 14 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 41cm, D.I: 26,5cm', 83.1, 'Ativo', 0, 'Un', 1),
('COMUM 14 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 41cm, D.I: 26,5cm', 101.8, 'Ativo', 0, 'Un', 1),
('COMUM 15 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 58cm, D.I: 32cm', 119.4, 'Ativo', 0, 'Un', 1),
('COMUM 15 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 58cm, D.I: 32cm', 157.2, 'Ativo', 0, 'Un', 1),
('COMUM 15 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 58cm, D.I: 32cm', 192.6, 'Ativo', 0, 'Un', 1),
('COMUM 17 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 64cm, D.S: 62cm, D.I: 34cm', 156.7, 'Ativo', 0, 'Un', 1),
('COMUM 17 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 64cm, D.S: 62cm, D.I: 34cm', 206.3, 'Ativo', 0, 'Un', 1),
('COMUM 17 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 64cm, D.S: 62cm, D.I: 34cm', 252.8, 'Ativo', 0, 'Un', 1),
('COPA 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 35cm, D.I: 20,5cm', 31.1, 'Ativo', 0, 'Un', 1),
('COPA 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 35cm, D.I: 20,5cm', 40.9, 'Ativo', 0, 'Un', 1),
('COPA 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 35cm, D.I: 20,5cm', 50.1, 'Ativo', 0, 'Un', 1),
('COPA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 36cm, D.S: 38cm, D.I: 24cm', 43.6, 'Ativo', 0, 'Un', 1),
('COPA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 36cm, D.S: 38cm, D.I: 24cm', 57.4, 'Ativo', 0, 'Un', 1),
('COPA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 36cm, D.S: 38cm, D.I: 24cm', 70.3, 'Ativo', 0, 'Un', 1),
('COPA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 42cm, D.S: 45cm, D.I: 27cm', 60.6, 'Ativo', 0, 'Un', 1),
('COPA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 42cm, D.S: 45cm, D.I: 27cm', 79.8, 'Ativo', 0, 'Un', 1),
('COPA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 42cm, D.S: 45cm, D.I: 27cm', 97.7, 'Ativo', 0, 'Un', 1),
('COCO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15cm, D.S: 16cm, D.I: 9cm', 14.7, 'Ativo', 0, 'Un', 1),
('COCO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15cm, D.S: 16cm, D.I: 9cm', 19.5, 'Ativo', 0, 'Un', 1),
('COCO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 15cm, D.S: 16cm, D.I: 9cm', 23.8, 'Ativo', 0, 'Un', 1),
('COCO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 21cm, D.I: 15cm', 26.5, 'Ativo', 0, 'Un', 1),
('COCO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 21cm, D.I: 15cm', 34.9, 'Ativo', 0, 'Un', 1),
('COCO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 21cm, D.I: 15cm', 42.8, 'Ativo', 0, 'Un', 1),
('COCO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 26cm, D.I: 21,5cm', 40.4, 'Ativo', 0, 'Un', 1),
('COCO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 26cm, D.I: 21,5cm', 53.3, 'Ativo', 0, 'Un', 1),
('COCO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 26cm, D.I: 21,5cm', 65.3, 'Ativo', 0, 'Un', 1),
('EGITO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 42cm, D.I: 26cm', 205.9, 'Ativo', 0, 'Un', 1),
('EGITO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 42cm, D.I: 26cm', 270.9, 'Ativo', 0, 'Un', 1),
('EGITO - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 42cm, D.I: 26cm', 332.1, 'Ativo', 0, 'Un', 1),
('FARAÓ 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 33cm, D.S: 50cm, D.I: 20cm', 32.2, 'Ativo', 0, 'Un', 1),
('FARAÓ 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 33cm, D.S: 50cm, D.I: 20cm', 42.4, 'Ativo', 0, 'Un', 1),
('FARAÓ 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 33cm, D.S: 50cm, D.I: 20cm', 52, 'Ativo', 0, 'Un', 1),
('FARAÓ 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 45cm, D.S: 45cm, D.I: 27cm', 73.2, 'Ativo', 0, 'Un', 1),
('FARAÓ 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 45cm, D.S: 45cm, D.I: 27cm', 96.3, 'Ativo', 0, 'Un', 1),
('FARAÓ 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 45cm, D.S: 45cm, D.I: 27cm', 118, 'Ativo', 0, 'Un', 1),
('FARAÓ 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 51cm, D.I: 30cm', 99.5, 'Ativo', 0, 'Un', 1),
('FARAÓ 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 51cm, D.I: 30cm', 130.9, 'Ativo', 0, 'Un', 1),
('FARAÓ 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 51cm, D.I: 30cm', 160.5, 'Ativo', 0, 'Un', 1),
('ITALIA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 38cm, D.S: 42cm, D.I: 25cm', 61.6, 'Ativo', 0, 'Un', 1),
('ITALIA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 38cm, D.S: 42cm, D.I: 25cm', 81.1, 'Ativo', 0, 'Un', 1),
('ITALIA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 38cm, D.S: 42cm, D.I: 25cm', 99.4, 'Ativo', 0, 'Un', 1),
('ITALIA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 48cm, D.I: 30cm', 88.9, 'Ativo', 0, 'Un', 1),
('ITALIA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 48cm, D.I: 30cm', 117.1, 'Ativo', 0, 'Un', 1),
('ITALIA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 46cm, D.S: 48cm, D.I: 30cm', 143.5, 'Ativo', 0, 'Un', 1),
('ITALIA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 56cm, D.I: 35,5cm', 154.2, 'Ativo', 0, 'Un', 1),
('ITALIA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 56cm, D.I: 35,5cm', 202.9, 'Ativo', 0, 'Un', 1),
('ITALIA 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 54cm, D.S: 56cm, D.I: 35,5cm', 248.7, 'Ativo', 0, 'Un', 1),
('ITALIA 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 60cm, D.I: 38cm', 205.9, 'Ativo', 0, 'Un', 1),
('ITALIA 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 60cm, D.I: 38cm', 270.9, 'Ativo', 0, 'Un', 1),
('ITALIA 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 60cm, D.I: 38cm', 332.1, 'Ativo', 0, 'Un', 1),
('CITY GARDEN 001 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 25cm, D.I: 25cm', 83.4, 'Ativo', 0, 'Un', 1),
('CITY GARDEN 001 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 25cm, D.I: 25cm', 109.8, 'Ativo', 0, 'Un', 1),
('INDIANO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 30cm, D.I: 18cm', 33.1, 'Ativo', 0, 'Un', 1),
('INDIANO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 30cm, D.I: 18cm', 43.6, 'Ativo', 0, 'Un', 1),
('INDIANO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 33cm, D.I: 20cm', 33.1, 'Ativo', 0, 'Un', 1),
('INDIANO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 30cm, D.S: 33cm, D.I: 20cm', 43.6, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 47cm, D.S: 19cm, D.I: 16cm', 81.9, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 47cm, D.S: 19cm, D.I: 16cm', 107.8, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 58cm, D.S: 24cm, D.I: 19cm', 143.9, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 58cm, D.S: 24cm, D.I: 19cm', 189.4, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA INCLINADA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 47cm, D.S: 19cm, D.I: 16cm', 83.6, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA INCLINADA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 47cm, D.S: 19cm, D.I: 16cm', 110, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA INCLINADA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 58cm, D.S: 24cm, D.I: 19cm', 149.2, 'Ativo', 0, 'Un', 1),
('JARRA C/ ALÇA INCLINADA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 58cm, D.S: 24cm, D.I: 19cm', 196.3, 'Ativo', 0, 'Un', 1),
('JARRA PALMA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 14cm, D.I: 17cm', 17.1, 'Ativo', 0, 'Un', 1),
('JARRA PALMA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 14cm, D.I: 17cm', 22.5, 'Ativo', 0, 'Un', 1),
('JARRA PALMA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 33cm, D.S: 17cm, D.I: 19cm', 22.6, 'Ativo', 0, 'Un', 1),
('JARRA PALMA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 33cm, D.S: 17cm, D.I: 19cm', 29.8, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 8.7, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 11.6, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 14.1, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 9.8, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 12.9, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 15.8, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 11.6, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 15.3, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 18.7, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 13.2, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 17.4, 'Ativo', 0, 'Un', 1),
('PAREDE BABADO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 21.3, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 8.1, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 10.7, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 14cm, D.I: 7cm', 13.2, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 8.9, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 11.8, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 14.5, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 11.2, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 14.7, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 18, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 12.5, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 16.5, 'Ativo', 0, 'Un', 1),
('PAREDE LISO 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 20.2, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 12cm, D.I: 7cm', 6.9, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 12cm, D.I: 7cm', 9.2, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 12cm, D.I: 7cm', 11.3, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 14cm, D.I: 9,5cm', 8.9, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 14cm, D.I: 9,5cm', 11.8, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 10cm, D.S: 14cm, D.I: 9,5cm', 14.5, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 16cm, D.I: 12,5cm', 11.8, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 16cm, D.I: 12,5cm', 15.6, 'Ativo', 0, 'Un', 1),
('JARDINEIRA 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 16cm, D.I: 12,5cm', 19.1, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 26cm, D.I: 22cm', 25.8, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 26cm, D.I: 22cm', 34, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 26cm, D.I: 22cm', 41.7, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21,5cm, D.S: 31cm, D.I: 26cm', 35.7, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21,5cm, D.S: 31cm, D.I: 26cm', 47.1, 'Ativo', 0, 'Un', 1),
('JARDINEIRA CUIA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21,5cm, D.S: 31cm, D.I: 26cm', 57.6, 'Ativo', 0, 'Un', 1),
('POSEIDON - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 63,5cm, D.S: 40cm, D.I: 24cm', 150.3, 'Ativo', 0, 'Un', 1),
('POSEIDON - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 63,5cm, D.S: 40cm, D.I: 24cm', 197.8, 'Ativo', 0, 'Un', 1),
('POSEIDON - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 63,5cm, D.S: 40cm, D.I: 24cm', 242.5, 'Ativo', 0, 'Un', 1),
('LISBOA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 30cm, D.I: 22,5cm', 114.2, 'Ativo', 0, 'Un', 1),
('LISBOA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 30cm, D.I: 22,5cm', 150.3, 'Ativo', 0, 'Un', 1),
('LISBOA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 30cm, D.I: 22,5cm', 184.2, 'Ativo', 0, 'Un', 1),
('LISBOA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 35cm, D.I: 25cm', 143.1, 'Ativo', 0, 'Un', 1),
('LISBOA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 35cm, D.I: 25cm', 188.3, 'Ativo', 0, 'Un', 1),
('LISBOA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 60cm, D.S: 35cm, D.I: 25cm', 230.7, 'Ativo', 0, 'Un', 1),
('LISBOA 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 70cm, D.S: 44cm, D.I: 28,5cm', 175.5, 'Ativo', 0, 'Un', 1),
('LISBOA 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 70cm, D.S: 44cm, D.I: 28,5cm', 230.9, 'Ativo', 0, 'Un', 1),
('LISBOA 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 70cm, D.S: 44cm, D.I: 28,5cm', 283.1, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 28cm, D.S: 35cm, D.I: 19cm', 31.1, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 28cm, D.S: 35cm, D.I: 19cm', 40.9, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 28cm, D.S: 35cm, D.I: 19cm', 50.1, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 47cm, D.I: 27,5cm', 63.7, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 47cm, D.I: 27,5cm', 83.9, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 47cm, D.I: 27,5cm', 102.7, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 57cm, D.S: 51cm, D.I: 31cm', 80.9, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 57cm, D.S: 51cm, D.I: 31cm', 106.5, 'Ativo', 0, 'Un', 1),
('MARIA EUGENIA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 57cm, D.S: 51cm, D.I: 31cm', 130.6, 'Ativo', 0, 'Un', 1),
('MONTREAL 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 37cm, D.I: 22cm', 77.4, 'Ativo', 0, 'Un', 1),
('MONTREAL 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 37cm, D.I: 22cm', 101.9, 'Ativo', 0, 'Un', 1),
('MONTREAL 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 50cm, D.S: 37cm, D.I: 22cm', 124.8, 'Ativo', 0, 'Un', 1),
('MONTREAL 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 65cm, D.S: 40cm, D.I: 27cm', 109.1, 'Ativo', 0, 'Un', 1),
('MONTREAL 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 65cm, D.S: 40cm, D.I: 27cm', 143.6, 'Ativo', 0, 'Un', 1),
('MONTREAL 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 65cm, D.S: 40cm, D.I: 27cm', 175.9, 'Ativo', 0, 'Un', 1),
('MONTREAL 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 46cm, D.I: 29cm', 134.7, 'Ativo', 0, 'Un', 1),
('MONTREAL 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 46cm, D.I: 29cm', 177.4, 'Ativo', 0, 'Un', 1),
('MONTREAL 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 46cm, D.I: 29cm', 217.4, 'Ativo', 0, 'Un', 1),
('MONTREAL 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 100cm, D.S: 52cm, D.I: 31cm', 236.6, 'Ativo', 0, 'Un', 1),
('MONTREAL 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 100cm, D.S: 52cm, D.I: 31cm', 311.4, 'Ativo', 0, 'Un', 1),
('MONTREAL 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 100cm, D.S: 52cm, D.I: 31cm', 381.7, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA PÉTALA', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 16cm, D.S: 21cm, D.I: 12,5cm', 17.4, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA 0', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 15cm, D.I: 12cm', 6.6, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA 1', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 18cm, D.I: 16cm', 7.1, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA 2', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 21cm, D.I: 21cm', 9.9, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA 3', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 13cm, D.S: 26cm, D.I: 25,5cm', 12.8, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA ALTA 1', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9,5cm', 10.2, 'Ativo', 0, 'Un', 1),
('ORQUÍDEA ALTA 2', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 11,5cm', 12.3, 'Ativo', 0, 'Un', 1),
('PAREDE ORQUÍDEA 1 B/L', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 14cm, D.S: 17cm, D.I: 9cm', 12.2, 'Ativo', 0, 'Un', 1),
('PAREDE ORQUÍDEA 2 B/L', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 17cm, D.S: 20cm, D.I: 12cm', 14.3, 'Ativo', 0, 'Un', 1),
('PAREDE ORQUÍDEA 3 B/L', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 20cm, D.S: 23cm, D.I: 13,5cm', 15.6, 'Ativo', 0, 'Un', 1),
('PEZINHO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 2, 'Ativo', 0, 'Un', 1),
('PEZINHO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 2.6, 'Ativo', 0, 'Un', 1),
('PEZINHO - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 3.3, 'Ativo', 0, 'Un', 1),
('PRATO 01 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 10cm, D.I: 7cm', 3.1, 'Ativo', 0, 'Un', 1),
('PRATO 01 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 10cm, D.I: 7cm', 4.1, 'Ativo', 0, 'Un', 1),
('PRATO 01 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 10cm, D.I: 7cm', 4.9, 'Ativo', 0, 'Un', 1),
('PRATO 02 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 12cm, D.I: 8,5cm', 3.4, 'Ativo', 0, 'Un', 1),
('PRATO 02 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 12cm, D.I: 8,5cm', 4.5, 'Ativo', 0, 'Un', 1),
('PRATO 02 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 12cm, D.I: 8,5cm', 5.5, 'Ativo', 0, 'Un', 1),
('PRATO 03 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 14cm, D.I: 10,5cm', 3.6, 'Ativo', 0, 'Un', 1),
('PRATO 03 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 14cm, D.I: 10,5cm', 4.7, 'Ativo', 0, 'Un', 1),
('PRATO 03 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 14cm, D.I: 10,5cm', 5.8, 'Ativo', 0, 'Un', 1),
('PRATO 05 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 16cm, D.I: 12cm', 4.1, 'Ativo', 0, 'Un', 1),
('PRATO 05 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 16cm, D.I: 12cm', 5.5, 'Ativo', 0, 'Un', 1),
('PRATO 05 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 16cm, D.I: 12cm', 6.6, 'Ativo', 0, 'Un', 1),
('PRATO 06 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 18cm, D.I: 15cm', 5.9, 'Ativo', 0, 'Un', 1),
('PRATO 06 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 18cm, D.I: 15cm', 7.8, 'Ativo', 0, 'Un', 1),
('PRATO 06 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 18cm, D.I: 15cm', 9.6, 'Ativo', 0, 'Un', 1),
('PRATO 07 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 20cm, D.I: 16,5cm', 7.4, 'Ativo', 0, 'Un', 1),
('PRATO 07 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 20cm, D.I: 16,5cm', 9.8, 'Ativo', 0, 'Un', 1),
('PRATO 07 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 20cm, D.I: 16,5cm', 11.9, 'Ativo', 0, 'Un', 1),
('PRATO 08 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 23cm, D.I: 18,5cm', 12.3, 'Ativo', 0, 'Un', 1),
('PRATO 08 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 23cm, D.I: 18,5cm', 16.2, 'Ativo', 0, 'Un', 1),
('PRATO 08 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,2cm, D.S: 23cm, D.I: 18,5cm', 19.9, 'Ativo', 0, 'Un', 1),
('PRATO 10 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 26cm, D.I: 21,5cm', 14.8, 'Ativo', 0, 'Un', 1),
('PRATO 10 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 26cm, D.I: 21,5cm', 18.6, 'Ativo', 0, 'Un', 1),
('PRATO 10 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 26cm, D.I: 21,5cm', 22.8, 'Ativo', 0, 'Un', 1),
('PRATO 11 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 28cm, D.I: 23,5cm', 16, 'Ativo', 0, 'Un', 1),
('PRATO 11 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 28cm, D.I: 23,5cm', 21.1, 'Ativo', 0, 'Un', 1),
('PRATO 11 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,3cm, D.S: 28cm, D.I: 23,5cm', 25.9, 'Ativo', 0, 'Un', 1),
('PRATO 13 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 34cm, D.I: 30cm', 19.9, 'Ativo', 0, 'Un', 1),
('PRATO 13 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 34cm, D.I: 30cm', 26.6, 'Ativo', 0, 'Un', 1),
('PRATO 13 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 34cm, D.I: 30cm', 32.1, 'Ativo', 0, 'Un', 1),
('PRATO 14 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 38cm, D.I: 32cm', 22.8, 'Ativo', 0, 'Un', 1),
('PRATO 14 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 38cm, D.I: 32cm', 30.1, 'Ativo', 0, 'Un', 1),
('PRATO 14 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,4cm, D.S: 38cm, D.I: 32cm', 36.8, 'Ativo', 0, 'Un', 1),
('PRATO 15 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 43cm, D.I: 37cm', 30.1, 'Ativo', 0, 'Un', 1),
('PRATO 15 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 43cm, D.I: 37cm', 39.7, 'Ativo', 0, 'Un', 1),
('PRATO 15 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 43cm, D.I: 37cm', 48.6, 'Ativo', 0, 'Un', 1),
('PRATO 17 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 46cm, D.I: 41cm', 39.5, 'Ativo', 0, 'Un', 1),
('PRATO 17 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 46cm, D.I: 41cm', 52, 'Ativo', 0, 'Un', 1),
('PRATO 17 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 0,5cm, D.S: 46cm, D.I: 41cm', 63.7, 'Ativo', 0, 'Un', 1),
('QUARTETO DECORATIVO', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 32.8, 'Ativo', 0, 'Un', 1),
('REAL 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 37cm, D.I: 22cm', 97.6, 'Ativo', 0, 'Un', 1),
('REAL 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 37cm, D.I: 22cm', 128.4, 'Ativo', 0, 'Un', 1),
('REAL 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 49cm, D.S: 37cm, D.I: 22cm', 157.5, 'Ativo', 0, 'Un', 1),
('REAL 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 43cm, D.I: 25,5cm', 125.2, 'Ativo', 0, 'Un', 1),
('REAL 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 43cm, D.I: 25,5cm', 164.7, 'Ativo', 0, 'Un', 1),
('REAL 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 62cm, D.S: 43cm, D.I: 25,5cm', 201.9, 'Ativo', 0, 'Un', 1),
('REAL 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 53cm, D.I: 29,5cm', 175.5, 'Ativo', 0, 'Un', 1),
('REAL 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 53cm, D.I: 29,5cm', 230.9, 'Ativo', 0, 'Un', 1),
('REAL 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 53cm, D.I: 29,5cm', 283.1, 'Ativo', 0, 'Un', 1),
('REAL 4 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 90cm, D.S: 50cm, D.I: 32cm', 236.3, 'Ativo', 0, 'Un', 1),
('REAL 4 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 90cm, D.S: 50cm, D.I: 32cm', 310.9, 'Ativo', 0, 'Un', 1),
('REAL 4 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 90cm, D.S: 50cm, D.I: 32cm', 381.2, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 38.4, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 50.6, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 62, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 64.1, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 84.4, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO LISO - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 103.5, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 41.5, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 54.6, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 1cm, D.S: 25cm, D.I: 30cm', 66.9, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 66.6, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 87.7, 'Ativo', 0, 'Un', 1),
('REDENTOR TORTO RÚST. - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 2cm, D.S: 33cm, D.I: 38cm', 107.5, 'Ativo', 0, 'Un', 1),
('REX SIMPLES - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 27cm, D.I: 19,5cm', 28.3, 'Ativo', 0, 'Un', 1),
('REX SIMPLES - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 27cm, D.I: 19,5cm', 37.3, 'Ativo', 0, 'Un', 1),
('REX SIMPLES - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 22cm, D.S: 27cm, D.I: 19,5cm', 45.7, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 30cm, D.I: 18cm', 31.2, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 30cm, D.I: 18cm', 41.1, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 0 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 30cm, D.I: 18cm', 50.3, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 22cm', 55.8, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 22cm', 73.5, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 37cm, D.S: 38cm, D.I: 22cm', 90, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 43cm, D.I: 24,5cm', 73.3, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 43cm, D.I: 24,5cm', 96.4, 'Ativo', 0, 'Un', 1),
('SÃO PAULO 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 43cm, D.S: 43cm, D.I: 24,5cm', 118.2, 'Ativo', 0, 'Un', 1),
('TINA 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 36cm, D.I: 23,5cm', 31.1, 'Ativo', 0, 'Un', 1),
('TINA 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 36cm, D.I: 23,5cm', 40.9, 'Ativo', 0, 'Un', 1),
('TINA 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 24cm, D.S: 36cm, D.I: 23,5cm', 50.1, 'Ativo', 0, 'Un', 1),
('TINA 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 29,5cm', 38.6, 'Ativo', 0, 'Un', 1),
('TINA 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 29,5cm', 50.8, 'Ativo', 0, 'Un', 1),
('TINA 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 26cm, D.S: 32cm, D.I: 29,5cm', 62.3, 'Ativo', 0, 'Un', 1),
('TOSCANO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 45cm, D.I: 31cm', 229.3, 'Ativo', 0, 'Un', 1),
('TOSCANO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 45cm, D.I: 31cm', 301.7, 'Ativo', 0, 'Un', 1),
('TOSCANO - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 80cm, D.S: 45cm, D.I: 31cm', 369.8, 'Ativo', 0, 'Un', 1),
('TRONCO P/ ORQUIDEA', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 6,5cm, D.I: 14cm', 16.4, 'Ativo', 0, 'Un', 1),
('TRIVIAL 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 20cm, D.I: 11,5cm', 7.1, 'Ativo', 0, 'Un', 1),
('TRIVIAL 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 20cm, D.I: 11,5cm', 9.4, 'Ativo', 0, 'Un', 1),
('TRIVIAL 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 18cm, D.S: 20cm, D.I: 11,5cm', 11.5, 'Ativo', 0, 'Un', 1),
('TRIVIAL 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 22,5cm, D.I: 14cm', 8.9, 'Ativo', 0, 'Un', 1),
('TRIVIAL 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 22,5cm, D.I: 14cm', 11.8, 'Ativo', 0, 'Un', 1),
('TRIVIAL 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 21cm, D.S: 22,5cm, D.I: 14cm', 14.4, 'Ativo', 0, 'Un', 1),
('VIOLETA - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 15cm, D.I: 12cm', 5.9, 'Ativo', 0, 'Un', 1),
('VIOLETA - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 15cm, D.I: 12cm', 7.7, 'Ativo', 0, 'Un', 1),
('VIOLETA - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 15cm, D.I: 12cm', 9.4, 'Ativo', 0, 'Un', 1),
('VIETNAM 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 25cm, D.I: 14cm', 22.3, 'Ativo', 0, 'Un', 1),
('VIETNAM 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 25cm, D.I: 14cm', 29.4, 'Ativo', 0, 'Un', 1),
('VIETNAM 1 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 25cm, D.S: 25cm, D.I: 14cm', 36, 'Ativo', 0, 'Un', 1),
('VIETNAM 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 31cm, D.S: 30cm, D.I: 18cm', 29.2, 'Ativo', 0, 'Un', 1),
('VIETNAM 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 31cm, D.S: 30cm, D.I: 18cm', 38.4, 'Ativo', 0, 'Un', 1),
('VIETNAM 2 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 31cm, D.S: 30cm, D.I: 18cm', 47.1, 'Ativo', 0, 'Un', 1),
('VIETNAM 3 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 35cm, D.I: 22cm', 42.8, 'Ativo', 0, 'Un', 1),
('VIETNAM 3 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 35cm, D.I: 22cm', 56.4, 'Ativo', 0, 'Un', 1),
('VIETNAM 3 - Fulget', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 40cm, D.S: 35cm, D.I: 22cm', 69.2, 'Ativo', 0, 'Un', 1),
('BEBEDOR PASSARO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 4,5cm, D.S: 9cm, D.I: 9,5cm', 3, 'Ativo', 0, 'Un', 1),
('BEBEDOR PASSARO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 4,5cm, D.S: 9cm, D.I: 9,5cm', 3.9, 'Ativo', 0, 'Un', 1),
('BEBEDOR PASSARO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 6cm, D.S: 11cm, D.I: 10,5cm', 3.4, 'Ativo', 0, 'Un', 1),
('BEBEDOR PASSARO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 6cm, D.S: 11cm, D.I: 10,5cm', 4.5, 'Ativo', 0, 'Un', 1),
('CASA DE PÁSSARO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 20 x 18', 35.2, 'Ativo', 0, 'Un', 1),
('CASA DE PÁSSARO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 20 x 18', 46.4, 'Ativo', 0, 'Un', 1),
('CASA JOÃO DE BARRO - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 18 x 20', 26.2, 'Ativo', 0, 'Un', 1),
('CASA JOÃO DE BARRO - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 18 x 20', 34.4, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 0 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 18cm, D.I: 15cm', 6.4, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 0 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 8cm, D.S: 18cm, D.I: 15cm', 8.3, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 1 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 22cm, D.I: 20cm', 8.3, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 1 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 9cm, D.S: 22cm, D.I: 20cm', 10.9, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 2 - Natural', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 25cm, D.I: 22cm', 10.4, 'Ativo', 0, 'Un', 1),
('COMEDOR DE CÃO 2 - Verniz ou Vecchio', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Alt: 11cm, D.S: 25cm, D.I: 22cm', 13.6, 'Ativo', 0, 'Un', 1),
('MINI BEGÔNIA 1 (Pct 07 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 5,5 x 5,5', 16.4, 'Ativo', 0, 'Pct', 1),
('MINI BEGÔNIA 2 (Pct 05 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 6,7 x 8', 14.7, 'Ativo', 0, 'Pct', 1),
('MINI BEGÔNIA 3 (Pct 05 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 8 x 10', 26.3, 'Ativo', 0, 'Pct', 1),
('MINI DEDAL (Pct 50 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 2,5 x 3', 61.7, 'Ativo', 0, 'Pct', 1),
('MINI COPO (Pct 05 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 8 x 7,1', 17.6, 'Ativo', 0, 'Pct', 1),
('MINI COMUM (Pct 50 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 3,8 x 4', 78.5, 'Ativo', 0, 'Pct', 1),
('MINI COMUM 4.0 (Pct 12 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 5,1 x 4,5', 22.4, 'Ativo', 0, 'Pct', 1),
('MINI COMUM 3.0 (Pct 12 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 5 x 6', 28.2, 'Ativo', 0, 'Pct', 1),
('MINI COMUM 2.0 Pacote com 10 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 6,2 x 7,6', 30.4, 'Ativo', 0, 'Pct', 1),
('MINI COMUM 0.0 Pacote com 08 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 8 x 9,8', 31.1, 'Ativo', 0, 'Pct', 1),
('MINI ITALIA (Pct 05 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 6,5 x 7', 14.7, 'Ativo', 0, 'Pct', 1),
('MINI PAREDE 3.0 (Pct 08 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 5 x 6', 34.6, 'Ativo', 0, 'Pct', 1),
('MINI PAREDE 2.0 (Pct 07 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 6,7 x 8', 39.6, 'Ativo', 0, 'Pct', 1),
('MINI PAREDE 0.0 (Pct 05 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 8 x 9,8', 40, 'Ativo', 0, 'Pct', 1),
('MINI SUCULENTA 1 (Pct 10 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 3,5 x 8,5', 29.3, 'Ativo', 0, 'Pct', 1),
('MINI SUCULENTA 2 (Pct 07 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 5,5 x 13,7', 45.1, 'Ativo', 0, 'Pct', 1),
('MINI TIGELA (Pct 13 pçs)', 'ABC CERÂMICA', 'Vasos de Cerâmica', 'Medidas: 3,6 x 5,6', 26.3, 'Ativo', 0, 'Pct', 1),
('ARGILA EXPANDIDA', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 50.3, 'Ativo', 0, 'Un', 1),
('CASCA DE PINUS POLIDA', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 34, 'Ativo', 0, 'Un', 1),
('FONTE MINI ATLANTA', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 189.5, 'Ativo', 0, 'Un', 1),
('FONTE MINI TUNES', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 200, 'Ativo', 0, 'Un', 1),
('FONTE ART. 004 - OFURO', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 327.6, 'Ativo', 0, 'Un', 1),
('LIMITADOR DE GRAMA (mini borda)', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 128.5, 'Ativo', 0, 'Un', 1),
('MANTA GEOTEXTIL', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 492, 'Ativo', 0, 'Un', 1),
('MUSGO VERDE NATURAL', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 129.2, 'Ativo', 0, 'Un', 1),
('PEDRISCO COLORIDO (cores variadas)', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 81.9, 'Ativo', 0, 'Un', 1),
('SUBSTRATO PARA ORQUIDEA', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 83.8, 'Ativo', 0, 'Un', 1),
('TERRA VEGETAL', 'ABC CERÂMICA', 'Vasos de Cerâmica', '', 10.8, 'Ativo', 0, 'Un', 1);
